// src/plans/Woche-4-2025-10-20.zh.jsx
import React, { useEffect, useMemo, useRef, useState } from "react";
import { exportPDFById, exportHTMLById } from "../utils/exporters";
import { buildEmbedCss } from "../utils/embedCss";
import { UI } from "../i18n-ui";
import { pickText, pickList } from "../i18n-data";

export const meta = {
  title: "第4周",
  startDate: "2025-10-20",
  id: "woche-4-2025-10-20-zh",
  lang: "zh",
  sidebar: "[ZH] 第4周 (2025-10-20)",
};
const FILE_BASE = "第4周 2025-10-20";

const UI_TITLES = {
  main: "吉卜力厨房 – 第4周",
  list: "吉卜力厨房 – 购物清单 – 第4周",
};

const COLORS = {
  pageBg: "#FAF7F1",
  text: "#111827",
  border: "rgba(0,0,0,.10)",
  panelBG70: "rgba(255,255,255,.70)",
  panelBG80: "rgba(255,255,255,.80)",
  white: "#FFFFFF",
  emerald: "#059669",
  amber: "#f59e0b",
  sky: "#0284c7",
  neutral: "#404040",
  indigo: "#4f46e5",
  btnShadow: "0 6px 20px rgba(0,0,0,.12)",
};

const cardPanelStyle = {
  background: COLORS.panelBG70,
  borderRadius: 18,
  padding: 20,
  boxShadow: COLORS.btnShadow,
  border: `1px solid ${COLORS.border}`,
};

const cardMainStyle = {
  background: COLORS.white,
  borderRadius: 18,
  padding: 22,
  boxShadow: COLORS.btnShadow,
  border: `1px solid ${COLORS.border}`,
};

const PROMPT_HEADER =
  "超干净的料理照片，柔和日光，自上而下拍摄，粉色背景，可见蒸汽，孕期友好（无生鱼/生蛋），温和的亚洲家常（日/中/韩），家庭友好";

const buildPrompt = (a, b) => `${a}\n${b}`;

/* -------------------- Safe helpers -------------------- */

const pickListSafe = (v, lang) => {
  try {
    const out = pickList(v, lang);
    return Array.isArray(out) ? out.filter((x) => x != null && x !== "") : [];
  } catch (e) {
    console.warn("[ZH] pickListSafe fallback -> []", e);
    return [];
  }
};

const safeArr = (v) => (Array.isArray(v) ? v : []);
const safeObj = (v) => (v && typeof v === "object" ? v : {});
const asList = (v, lang) => {
  try {
    const out = pickList(v, lang);
    return Array.isArray(out) ? out : [];
  } catch {
    return [];
  }
};

/* -------------------- DATA（21个食谱）-------------------- */
const DATA = [
  {
    id: "mo-f",
    title: "三文鱼丝豆腐粥（お粥）",
    desc: "日式Okayu，温和米粥配蒸熟三文鱼与嫩豆腐；灵感来自 Just One Cookbook。",
    story: "Okayu源自日本，常见于早餐或感冒时食用。入秋后尤为受欢迎——适合安静的清晨与温柔的开始。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈20 g/人",
    ingredients: [
      "大米（生） 90 g",
      "水 800 ml",
      "三文鱼柳 120 g",
      "内酯豆腐 200 g",
      "姜 10 g",
      "葱 20 g",
      "低钠酱油 10 ml",
    ],
    steps: [
      "淘米，加水煮开后小火煮25–30分钟至软糯。",
      "在粥上方蒸三文鱼8–10分钟，取出弄碎。",
      "加入豆腐，姜末与酱油微调味，撒葱花稍焖即可。",
    ],
    checks: "胃炎——温和暖胃 · 糖友✓ ≈70 g KH · 孕期✓ 鱼全熟、低汞",
    swaps: "内酯豆腐 ↔ 老豆腐；三文鱼 ↔ 鳕鱼；替代菜：牛丼（瘦牛肉）或姜烧猪（瘦猪肉）——米量可减半。",
    side: "温热大麦茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Creamy Japanese okayu porridge, flaked cooked salmon, silken tofu cubes, scallions, steam rising"),
  },
  {
    id: "mo-m",
    title: "温和拌饭（비빔밥）— 辣椒可选",
    desc: "韩式蔬菜牛肉拌饭；辣椒分开另给；灵感来自 My Korean Kitchen。",
    story: "拌饭源自韩国，四季皆宜。热食适合午餐或晚间均衡碗饭，不需辣也很香。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈31 g/人",
    ingredients: [
      "糙米（生） 90 g",
      "瘦牛肉糜 220 g",
      "菠菜 200 g",
      "胡萝卜 120 g",
      "香菇 120 g",
      "鸡蛋 2 Stück",
      "低钠酱油 20 ml",
      "香油 10 ml",
    ],
    steps: [
      "煮饭；蔬菜汆烫或少油快炒。",
      "牛肉糜炒熟至全熟，温和调味。",
      "装碗，鸡蛋全熟煎（蛋黄凝固）。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 蛋全熟、肉全熟",
    swaps: "牛肉糜 ↔ 火鸡糜；糙米 ↔ 寿司米；替代菜：牛丼（温和）或猪丼（低钠酱汁）。",
    side: "辣酱另碟。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Colorful bibimbap bowl, brown rice, sautéed spinach carrots shiitake, fully cooked egg, no chili on top"),
  },
  {
    id: "mo-a",
    title: "温和麻婆豆腐（麻婆豆腐）— 辣椒可选",
    desc: "中式经典的温和味噌系酱汁版本；可单独配辣；灵感来自 Omnivore’s Cookbook。",
    story: "麻婆豆腐源自川菜；家常温和版在中国各地都很常见。适合下班后快手暖胃，不辣也下饭。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "老豆腐 400 g",
      "香菇 150 g",
      "浅色味噌 20 g",
      "蔬菜高汤 300 ml",
      "低钠酱油 20 ml",
      "蒜 1 瓣",
      "姜 10 g",
      "玉米淀粉 10 g",
      "糙米（生） 90 g",
    ],
    steps: [
      "煮饭；香菇煸软。",
      "高汤+味噌+酱油加热；入豆腐小火煨4–5分钟。",
      "淀粉水勾薄芡，浇在米饭上食用。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 全熟",
    swaps: "糙米 ↔ 白米；味噌 ↔ 温和豆瓣/黄豆酱；替代菜：温和版猪肉末麻婆（不辣）或牛肉豆腐煎炒。",
    side: "清蒸小白菜。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Mild mapo tofu with mushrooms, glossy light-brown sauce, over brown rice, no chili flakes"),
  },
  // 周二
  {
    id: "di-f",
    title: "三文鱼饭团 & 味噌汤（おにぎり・味噌汁）",
    desc: "三文鱼内馅饭团与温和味噌汤；灵感来自 Just One Cookbook。",
    story: "饭团属于日本便当文化，四季皆宜。配味噌汤是清淡早餐或外带小食——适合温和的早晨。",
    target: "≈78 g KH gesamt (2 P.) · 蛋白质 ≈27 g/人",
    ingredients: [
      "寿司米（生） 100 g",
      "三文鱼柳 150 g",
      "海苔 1 Blatt",
      "浅色味噌 20 g",
      "老豆腐 150 g",
      "裙带菜（干） 2 g",
      "水 900 ml",
      "低钠酱油 10 ml",
    ],
    steps: [
      "煮米，捏饭团；熟三文鱼撕碎作馅；外包海苔。",
      "味噌用热水化开（不沸腾），下豆腐与裙带菜略焖。",
      "酌量加酱油调整。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈78 g KH · 孕期✓ 鱼全熟，海藻少量",
    swaps: "寿司米 ↔ 糙米；三文鱼 ↔ 明太鱼/狭鳕；替代菜：猪肉碎盖饭（温和）或牛丼（瘦）。",
    side: "温和绿茶（可脱咖）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Two salmon onigiri with nori, small bowl of miso soup with tofu and wakame"),
  },
  {
    id: "di-m",
    title: "鸡肉河粉炒（河粉）",
    desc: "广式风味的温和炒河粉、蔬菜多；灵感来自 The Woks of Life。",
    story: "参考广东河粉（Ho Fun）。快手、四季皆宜——省时又均衡。",
    target: "≈74 g KH gesamt (2 P.) · 蛋白质 ≈39 g/人",
    ingredients: [
      "干河粉 80 g",
      "鸡胸肉 250 g",
      "彩椒 150 g",
      "小白菜 200 g",
      "洋葱 80 g",
      "胡萝卜 100 g",
      "低钠酱油 25 ml",
      "香油 10 ml",
    ],
    steps: [
      "河粉浸泡/焯水。",
      "鸡丝少油翻炒至全熟。",
      "下蔬菜，温和调味快速翻匀。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈74 g KH · 孕期✓ 鸡肉全熟",
    swaps: "河粉 ↔ 乌冬；鸡肉 ↔ 豆腐；替代菜：越式牛肉炒粉（温和）或小白菜猪里脊快炒（温和）。",
    side: "黄瓜片原味。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Stir-fried rice noodles with chicken and colorful vegetables, light sauce, no chili"),
  },
  {
    id: "di-a",
    title: "大酱汤配麦仁（된장찌개）",
    desc: "韩式大酱锅，醇厚但不辣；灵感来自 Seon Kyoung Longest。",
    story: "大酱汤是韩国家常汤品，秋冬尤受欢迎。风味足但温和——很适合惬意的夜晚。",
    target: "≈86 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "大酱 30 g",
      "老豆腐 300 g",
      "西葫芦 200 g",
      "土豆 200 g",
      "香菇 100 g",
      "洋葱 70 g",
      "水 800 ml",
      "低钠酱油 10 ml",
      "珍珠麦（生） 70 g",
    ],
    steps: [
      "大酱溶于水，蔬菜小火煮12–15分钟。",
      "加入豆腐丁略焖。",
      "珍珠麦分锅煮熟，搭配食用。",
    ],
    checks: "胃炎——醇厚不辣 · 糖友✓ ≈86 g KH · 孕期✓ 全熟",
    swaps: "珍珠麦 ↔ 米饭；豆腐 ↔ 火鸡胸；替代菜：豚汁（温和）或寿喜烧风瘦牛蔬煮（低糖）。",
    side: "温和腌黄瓜（无辣）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Korean soybean stew with tofu and vegetables in a clay pot, side of barley"),
  },
  // 周三
  {
    id: "mi-f",
    title: "南瓜粥配豆腐与毛豆（단호박죽）",
    desc: "丝滑南瓜米粥，高蛋白；灵感来自 Mom’s Korean Recipes。",
    story: "源自韩国，秋季应季南瓜。温和绵密——适合清晨或清淡晚餐。",
    target: "≈75 g KH gesamt (2 P.) · 蛋白质 ≈22 g/人",
    ingredients: [
      "南瓜（板栗/北海道） 400 g",
      "大米（生） 70 g",
      "老豆腐 200 g",
      "毛豆仁 100 g",
      "姜 8 g",
      "水 900 ml",
      "盐 少许",
    ],
    steps: [
      "南瓜+大米小火煮25分钟至软。",
      "打成细腻；入豆腐与毛豆再煮3–4分钟。",
      "温和调味。",
    ],
    checks: "胃炎——软暖 · 糖友✓ ≈75 g KH · 孕期✓ 全熟",
    swaps: "毛豆 ↔ 白腰豆；豆腐 ↔ 鸡胸丁；替代菜：牛丼（瘦）或日式姜烧猪（瘦）。",
    side: "温热米茶/大麦茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Golden pumpkin rice porridge, tofu cubes and green edamame, gentle steam"),
  },
  {
    id: "mi-m",
    title: "鸡肉西兰花乌冬汤（うどん）",
    desc: "日式清汤乌冬，清淡温和；灵感来自 Just One Cookbook。",
    story: "轻汤乌冬在日本四季常见，尤其冷月。柔和饱腹，适合午餐不吃辣。",
    target: "≈79 g KH gesamt (2 P.) · 蛋白质 ≈34 g/人",
    ingredients: [
      "乌冬（干） 110 g",
      "鸡胸肉 220 g",
      "西兰花 200 g",
      "洋葱 60 g",
      "浅色味噌 25 g",
      "水 1000 ml",
      "低钠酱油 15 ml",
    ],
    steps: [
      "汤底以味噌+酱油调和加热。",
      "鸡肉小火煮6–8分钟至全熟；蔬菜再煮3–4分钟。",
      "乌冬另煮，冲洗后入汤同煮片刻。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈79 g KH · 孕期✓ 鸡肉全熟",
    swaps: "乌冬 ↔ 荞麦面；鸡肉 ↔ 豆腐；替代菜：牛肉乌冬或猪肉乌冬（温和）。",
    side: "小碟黄瓜。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Light udon soup with chicken slices and broccoli in clear broth"),
  },
  {
    id: "mi-a",
    title: "姜丝清蒸鳕鱼 & 白米（清蒸鳕鱼）",
    desc: "粤式清蒸，细嫩易消化；灵感来自 Made With Lau。",
    story: "清蒸是粤菜经典技法。清爽温和，适合需要清淡的夜晚。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "鳕鱼柳 320 g",
      "大米（生） 90 g",
      "姜 15 g",
      "葱 30 g",
      "低钠酱油 15 ml",
      "香油 8 ml",
      "蔬菜高汤 100 ml",
    ],
    steps: [
      "鱼置姜片上，蒸8–10分钟至全熟。",
      "酱油+高汤加热，浇鱼，淋香油。",
      "米饭煮熟同食。",
    ],
    checks: "胃炎——清蒸 · 糖友✓ ≈70 g KH · 孕期✓ 鳕鱼全熟、低汞",
    swaps: "鳕鱼 ↔ 明太鱼；米饭 ↔ 糙米；替代菜：日式姜烧猪或姜汁牛肉条（温和）。",
    side: "清蒸西兰花。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Steamed cod with ginger and scallions, light glossy sauce, side bowl of rice"),
  },
    // 周四
  {
    id: "do-f",
    title: "玉子烧 & 味噌汤配小碗米饭（卵焼き・味噌汁）",
    desc: "日式早餐，煎蛋完全凝固；灵感来自 Just One Cookbook。",
    story: "玉子烧是日本经典早餐，也常入便当。配味噌汤，温和均衡地开启一天。",
    target: "≈62 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "鸡蛋 4 Stück",
      "老豆腐 150 g",
      "大米（生） 80 g",
      "浅色味噌 20 g",
      "裙带菜（干） 1 g",
      "葱 20 g",
      "水 800 ml",
      "低钠酱油 10 ml",
    ],
    steps: [
      "煮饭。玉子烧卷煎至完全凝固。",
      "煮味噌汤；下豆腐/裙带菜略焖。",
      "撒葱花上桌。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈62 g KH · 孕期✓ 蛋完全凝固",
    swaps: "米饭 ↔ 糙米；豆腐 ↔ 鸡胸丁；替代菜：牛肉乌冬（温和）作丰盛早餐。",
    side: "温热绿茶（低咖）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Japanese breakfast set with rolled omelet, small rice bowl, miso soup"),
  },
  {
    id: "do-m",
    title: "番茄炒蛋配豆腐 & 米饭（番茄炒蛋）",
    desc: "中式家常，酸甜温和；灵感来自 The Woks of Life。",
    story: "番茄炒蛋是中国最有名的家常菜之一。温和版本适合工作日的快速餐。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈28 g/人",
    ingredients: [
      "大米（生） 90 g",
      "鸡蛋 4 Stück",
      "老豆腐 200 g",
      "熟透番茄 400 g",
      "洋葱 60 g",
      "低钠酱油 10 ml",
      "菜籽油 10 ml",
    ],
    steps: [
      "煮饭；鸡蛋炒至全熟凝固。",
      "番茄与洋葱小火炖软；下豆腐稍焖。",
      "温和调味，配米饭食用。",
    ],
    checks: "胃炎——酸度温和、炖至软 · 糖友✓ ≈70 g KH · 孕期✓ 蛋全熟",
    swaps: "豆腐 ↔ 火鸡胸丁；米饭 ↔ 糙米；替代菜：青椒肉丝（温和）或牛肉彩椒炒（温和）。",
    side: "清蒸小白菜。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Tomato and egg stir-fry with tofu, served with rice, soft edges, no chili"),
  },
  {
    id: "do-a",
    title: "温和韩式烤肉风味火鸡 & 糙米（불고기）",
    desc: "韩式灵感的平底锅快炒，温和不辣；灵感来自 Maangchi。",
    story: "烤肉（Bulgogi）源自韩国，平底锅版四季常做。温和腌制、快炒出香——适合家庭晚餐。",
    target: "≈80 g KH gesamt (2 P.) · 蛋白质 ≈28 g/人",
    ingredients: [
      "火鸡胸肉 250 g",
      "糙米（生） 90 g",
      "洋葱 80 g",
      "胡萝卜 120 g",
      "蘑菇 150 g",
      "低钠酱油 25 ml",
      "香油 10 ml",
      "蒜 1 瓣",
      "梨（擦泥） 60 g",
    ],
    steps: [
      "火鸡肉与酱油/梨泥/蒜腌15分钟。",
      "少油快炒至全熟。",
      "下蔬菜略炒，配糙米食用。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈80 g KH · 孕期✓ 火鸡全熟",
    swaps: "火鸡 ↔ 鸡胸；糙米 ↔ 白米；替代菜：瘦牛烤肉或温和猪烤肉（不辣）。",
    side: "黄瓜片原味。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Mild bulgogi turkey with mushrooms and carrots, brown rice, no chili"),
  },
  // 周五
  {
    id: "fr-f",
    title: "鸡肉粥（鸡肉粥）",
    desc: "中式米粥配嫩鸡肉——柔和暖胃；灵感来自 The Woks of Life。",
    story: "粥在华南及东南亚非常常见，适合早餐或晚餐。温暖清淡——下雨天尤其舒服。",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈34 g/人",
    ingredients: [
      "大米（生） 90 g",
      "鸡胸肉 220 g",
      "姜 12 g",
      "胡萝卜 120 g",
      "水 1100 ml",
      "低钠酱油 10 ml",
      "葱 20 g",
    ],
    steps: [
      "米加水小火煮30分钟。",
      "鸡肉切小丁，入粥煮8–10分钟至全熟。",
      "温和调味，撒葱花。",
    ],
    checks: "胃炎——非常温和 · 糖友✓ ≈70 g KH · 孕期✓ 鸡肉全熟",
    swaps: "鸡肉 ↔ 豆腐；胡萝卜 ↔ 南瓜；替代菜：瘦猪粥或瘦牛粥（均温和）。",
    side: "温热花草茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Chicken congee in a deep bowl, shredded chicken, scallions, gentle steam"),
  },
  {
    id: "fr-m",
    title: "清爽意式蔬菜汤配豆腐（Minestrone）",
    desc: "意大利蔬菜浓汤，久煮温和不刺激。",
    story: "Minestrone常见于夏末到秋季。此轻盈版适合轻松的夜晚，温暖不厚重。",
    target: "≈69 g KH gesamt (2 P.) · 蛋白质 ≈39 g/人",
    ingredients: [
      "全麦意面（干） 60 g",
      "白腰豆（沥干） 200 g",
      "胡萝卜 150 g",
      "西芹 100 g",
      "番茄碎（passata） 250 ml",
      "西葫芦 150 g",
      "蔬菜高汤 800 ml",
      "橄榄油 10 ml",
      "帕玛森（巴氏杀菌，可选） 20 g",
      "老豆腐 300 g",
    ],
    steps: [
      "少油炒香蔬菜，加高汤/番茄碎小火煮20–25分钟。",
      "入豆腐/白腰豆再焖5分钟。",
      "意面另煮，最后拌入。",
    ],
    checks: "胃炎——久煮温和 · 糖友✓ ≈69 g KH · 孕期✓ 奶酪可选且需巴氏杀菌",
    swaps: "豆腐 ↔ 鸡胸丁；意面 ↔ 大麦；替代菜：日式素炒蔬+猪里脊（温和）或牛肉蔬炒（温和）。",
    side: "温热草本茶。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Light minestrone with vegetables and tofu, few wholegrain pasta pieces"),
  },
  {
    id: "fr-a",
    title: "烤三文鱼照烧配西兰花 & 米饭（照り焼き）",
    desc: "日式灵感，低钠酱油烤制；灵感来自 Just One Cookbook。",
    story: "照烧是日本的调味与做法之一。烤箱版更省事——适合清凉夜晚的省时晚餐。",
    target: "≈75 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "三文鱼柳 320 g",
      "大米（生） 90 g",
      "西兰花 300 g",
      "低钠酱油 25 ml",
      "味醂（可选） 10 ml",
      "蜂蜜（可选） 5 g",
      "姜 10 g",
    ],
    steps: [
      "调酱（酱油+少许味醂/蜂蜜+姜）。",
      "刷在三文鱼上，200°C烤12–14分钟。",
      "配米饭与蒸西兰花食用。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈75 g KH（甜度很低） · 孕期✓ 三文鱼全熟",
    swaps: "米饭 ↔ 糙米；西兰花 ↔ 小白菜；替代菜：日式姜烧猪（温和）或照烧牛肉（瘦）。",
    side: "温热绿茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Baked salmon with light teriyaki glaze, steamed broccoli and rice"),
  },
  // 周六
  {
    id: "sa-f",
    title: "蔬菜煎饼（야채전）",
    desc: "韩式蔬菜煎饼，脆边柔心；灵感来自 Maangchi。",
    story: "这类煎饼在韩国称为전，是家常的午后轻食。温和、营养、易做。",
    target: "≈68 g KH gesamt (2 P.) · 蛋白质 ≈25 g/人",
    ingredients: [
      "胡萝卜 100 g",
      "西葫芦 100 g",
      "洋葱 80 g",
      "鸡蛋 2 Stück",
      "面粉 80 g",
      "水 100 ml",
      "菜籽油 10 ml",
    ],
    steps: [
      "蔬菜切细丝。",
      "调面糊，拌蔬菜，平底锅两面煎金黄。",
      "配淡酱油蘸食。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈68 g KH · 孕期✓ 全熟",
    swaps: "蔬菜可随季节替换；替代菜：南瓜饼（温和甜）。",
    side: "温热绿茶。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Korean vegetable pancake, crispy edges, colorful strips of carrot and zucchini"),
  },
  {
    id: "sa-m",
    title: "鸡肉咖喱饭（日式温和）",
    desc: "日式家常咖喱，温和无辣；灵感来自 Just One Cookbook。",
    story: "日本咖喱源自英印风改良。甜口浓香，适合秋季。",
    target: "≈82 g KH gesamt (2 P.) · 蛋白质 ≈30 g/人",
    ingredients: [
      "鸡胸肉 250 g",
      "大米（生） 90 g",
      "土豆 200 g",
      "胡萝卜 150 g",
      "洋葱 100 g",
      "温和咖喱块 40 g",
      "水 800 ml",
    ],
    steps: [
      "炒洋葱出香，加鸡肉炒熟。",
      "入土豆胡萝卜加水炖至软。",
      "溶入咖喱块，焖5分钟。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈82 g KH · 孕期✓ 鸡肉全熟",
    swaps: "鸡 ↔ 豆腐；咖喱 ↔ 淡味黄油炖菜；替代菜：牛肉咖喱（温和）。",
    side: "清蒸青菜。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Japanese mild curry with chicken, potatoes, carrots, over rice"),
  },
  {
    id: "sa-a",
    title: "味噌烤茄子 & 糙米",
    desc: "味噌烤茄子（日式）甜香软糯；灵感来自 Just One Cookbook。",
    story: "茄子味噌烧是家常素菜代表。浓香中带甜，非常适合配糙米。",
    target: "≈75 g KH gesamt (2 P.) · 蛋白质 ≈20 g/人",
    ingredients: [
      "茄子 300 g",
      "浅色味噌 25 g",
      "味醂 10 ml",
      "蜂蜜 5 g",
      "糙米（生） 90 g",
      "香油 8 ml",
    ],
    steps: [
      "茄子对半切，表面划纹。",
      "混味噌+味醂+蜂蜜刷上，180°C 烤15分钟。",
      "配糙米食用。",
    ],
    checks: "胃炎——软嫩 · 糖友✓ ≈75 g KH · 孕期✓ 全熟",
    swaps: "味噌 ↔ 酱油；茄子 ↔ 南瓜；替代菜：炒南瓜豆腐（温和）。",
    side: "温热米茶。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Japanese miso-glazed eggplant halves on a plate, glossy glaze, brown rice side"),
  },
  // 周日
  {
    id: "so-f",
    title: "温豆腐汤（순두부찌개，去辣版）",
    desc: "经典韩式嫩豆腐汤的去辣温和版；灵感来自 Maangchi。",
    story: "嫩豆腐汤原属韩国家常。去辣后依然香浓柔和。",
    target: "≈68 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "嫩豆腐 400 g",
      "鸡蛋 2 Stück",
      "洋葱 100 g",
      "香菇 80 g",
      "低钠酱油 20 ml",
      "大酱 20 g",
      "水 700 ml",
      "大米（生） 80 g",
    ],
    steps: [
      "煮饭。",
      "锅中炒香洋葱、香菇，加水+大酱煮5分钟。",
      "入嫩豆腐煨3分钟，最后打蛋煮至凝固。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈68 g KH · 孕期✓ 全熟",
    swaps: "鸡蛋 ↔ 豆腐丁；替代菜：味噌豆腐汤或蔬菜豆腐锅。",
    side: "温热绿茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Mild Korean soft tofu stew without chili, egg set on top, gentle steam"),
  },
  {
    id: "so-m",
    title: "味噌拉面（无辣）",
    desc: "温和味噌拉面，蔬菜多蛋白足；灵感来自 Chopstick Chronicles。",
    story: "味噌拉面是日本国民美食。温和版不辣，风味依然深。",
    target: "≈85 g KH gesamt (2 P.) · 蛋白质 ≈35 g/人",
    ingredients: [
      "拉面（干） 120 g",
      "鸡胸肉 200 g",
      "玉米粒 80 g",
      "豆芽 100 g",
      "浅色味噌 25 g",
      "水 900 ml",
      "低钠酱油 15 ml",
    ],
    steps: [
      "味噌+酱油调汤底，加水煮开。",
      "下鸡肉煮熟，入拉面、玉米粒、豆芽。",
      "全熟即可。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈85 g KH · 孕期✓ 全熟",
    swaps: "鸡 ↔ 豆腐；拉面 ↔ 乌冬；替代菜：日式素拉面（温和）。",
    side: "温热水或绿茶。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Miso ramen with corn, sprouts and chicken slices, no chili"),
  },
  {
    id: "so-a",
    title: "蔬菜杂烩饭（야채덮밥）",
    desc: "韩式灵感蔬菜盖饭，温和少油。",
    story: "一锅煮的盖饭形式。调味轻，蔬菜丰富。",
    target: "≈80 g KH gesamt (2 P.) · 蛋白质 ≈28 g/人",
    ingredients: [
      "糙米（生） 90 g",
      "豆腐 250 g",
      "胡萝卜 100 g",
      "西葫芦 100 g",
      "洋葱 60 g",
      "低钠酱油 15 ml",
      "香油 10 ml",
    ],
    steps: [
      "炒蔬菜与豆腐，加酱油调味。",
      "配糙米食用。",
      "撒少许葱末。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈80 g KH · 孕期✓ 全熟",
    swaps: "豆腐 ↔ 鸡胸丁；糙米 ↔ 白米。",
    side: "温热茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Korean vegetable rice bowl, brown rice base, colorful toppings, no chili"),
  },
];

/* -------------------- 导出 -------------------- */
export default DATA;