import React from "react";
import { exportPDFById, exportHTMLById } from "../utils/exporters";
import { buildEmbedCss } from "../utils/embedCss";
import { UI } from "../i18n-ui";
import { pickText, pickList } from "../i18n-data";

/* ---------- Meta ---------- */
export const meta = {
  title: "第8周",
  startDate: "2025-11-17",
  id: "woche-8-2025-11-17-zh",
  lang: "zh",
  sidebar: "[ZH] 第8周 (2025-11-17)",
};
const FILE_BASE = "第8周 2025-11-17";

/* ---------- UI ----------- */
const UI_TITLES = {
  main: "吉卜力厨房 – 第8周",
  list: "吉卜力厨房 – 购物清单 – 第8周",
};

/* ---------- Styles ---------- */
const COLORS = {
  pageBg: "#FAF7F1",
  text: "#111827",
  border: "rgba(0,0,0,.10)",
  panelBG70: "rgba(255,255,255,.70)",
  panelBG80: "rgba(255,255,255,.80)",
  white: "#FFFFFF",
  emerald: "#059669",
  amber: "#f59e0b",
  sky: "#0284c7",
  neutral: "#404040",
  indigo: "#4f46e5",
  btnShadow: "0 6px 20px rgba(0,0,0,.12)",
};

const cardPanelStyle = {
  background: COLORS.panelBG70,
  borderRadius: 18,
  padding: 20,
  boxShadow: COLORS.btnShadow,
  border: `1px solid ${COLORS.border}`,
};

const cardMainStyle = {
  background: COLORS.white,
  borderRadius: 18,
  padding: 22,
  boxShadow: COLORS.btnShadow,
  border: `1px solid ${COLORS.border}`,
};

/* ---------- Prompts ---------- */
const PROMPT_HEADER =
  "Ultra-clean cookbook photo, soft daylight, top-down, pastel background, visible steam, pregnancy-safe (no raw fish or no raw egg), mild Asian home cooking (JP/CN/KR), family-friendly";
const buildPrompt = (a, b) => `${a}\n${b}`;

/* ---------- DAY HELPERS ---------- */
const DAYS_ORDER = ["mo", "di", "mi", "do", "fr", "sa", "so"];
const DAY_NAME_ZH = { mo: "周一", di: "周二", mi: "周三", do: "周四", fr: "周五", sa: "周六", so: "周日" };

/* ---------- DATA（21 道菜；以中/日/韩为主，最多 1 个意式） ---------- */
const DATA = [
  // 周一
  {
    id: "mo-f",
    title: "三文鱼丝豆腐粥（お粥）",
    desc: "日式Okayu，极为温和、低钠，暖胃开场。",
    story: "Okayu源自日本，常作早餐或病后调理，绵柔易消化，适合安静清晨。Inspiration: inspiriert von Just One Cookbook",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈20 g/人",
    ingredients: [
      "大米（生） 90 g",
      "水 800 ml",
      "三文鱼柳 120 g",
      "内酯豆腐 200 g",
      "姜 10 g",
      "葱 20 g",
      "低钠酱油 10 ml",
    ],
    steps: [
      "淘米加水煮沸后小火煮25–30分钟至绵软。",
      "在粥面蒸三文鱼8–10分钟，取出掰碎。",
      "入豆腐，姜末与酱油微调味；撒葱花焖1分钟。",
    ],
    checks: "胃炎——温和暖胃 · 糖友✓ ≈70 g KH · 孕期✓ 鱼全熟、低汞",
    swaps: "内酯豆腐 ↔ 老豆腐；三文鱼 ↔ 鳕鱼；小贴士：米量可按需下调。",
    side: "温热大麦茶；清爽黄瓜浅渍（无辣）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Creamy Japanese okayu, flaked cooked salmon, silken tofu, scallions, steam"),
  },
  {
    id: "mo-m",
    title: "温和拌饭（비빔밥）— 辣椒分开",
    desc: "韩式蔬菜牛肉拌饭；低钠，不直接加辣。",
    story: "拌饭是韩国代表性家常，四季皆宜。温热、配菜丰富的版本尤其适合午间。Inspiration: inspiriert von My Korean Kitchen",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈31 g/人",
    ingredients: [
      "糙米（生） 90 g",
      "瘦牛肉糜 220 g",
      "菠菜 200 g",
      "胡萝卜 120 g",
      "香菇 120 g",
      "鸡蛋 2 枚",
      "低钠酱油 20 ml",
      "香油 10 ml",
    ],
    steps: [
      "煮饭；蔬菜汆烫或少油快炒5–6分钟。",
      "牛肉糜炒熟至全熟6–8分钟，温和调味。",
      "鸡蛋全熟煎；整碗装盘，辣酱另碟。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 蛋/肉全熟",
    swaps: "牛肉糜 ↔ 火鸡糜；糙米 ↔ 寿司米。",
    side: "小碟黄瓜；温和泡菜（无辣）可选。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Colorful bibimbap with brown rice, cooked egg, vegetables, no chili on top"),
  },
  {
    id: "mo-a",
    title: "温和麻婆豆腐（麻婆豆腐）— 不辣版",
    desc: "味噌系清淡酱汁，家常柔和口味。",
    story: "麻婆豆腐源自川菜，这里做成不辣、暖胃的家常版，适合下班后快手。Inspiration: inspiriert von Omnivore’s Cookbook",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "老豆腐 400 g",
      "香菇 150 g",
      "浅色味噌 20 g",
      "蔬菜高汤 300 ml",
      "低钠酱油 20 ml",
      "蒜 1 瓣",
      "姜 10 g",
      "玉米淀粉 10 g",
      "糙米（生） 90 g",
    ],
    steps: [
      "煮饭30–35分钟；香菇煸软5分钟。",
      "高汤+味噌+酱油加热；豆腐煨4–5分钟。",
      "水淀粉勾薄芡，浇在米饭上。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 全熟",
    swaps: "糙米 ↔ 白米；味噌 ↔ 温和豆瓣/黄豆酱。",
    side: "清蒸小白菜；温热茶饮。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Mild mapo tofu with mushrooms over brown rice, no chili"),
  },

  // 周二
  {
    id: "di-f",
    title: "三文鱼饭团 & 味噌汤（おにぎり・味噌汁）",
    desc: "熟三文鱼内馅饭团，配温和味噌汤。",
    story: "饭团属于日本便当文化，方便可口；配味噌汤，是轻盈暖胃的早餐。Inspiration: inspiriert von Just One Cookbook",
    target: "≈78 g KH gesamt (2 P.) · 蛋白质 ≈27 g/人",
    ingredients: [
      "寿司米（生） 100 g",
      "三文鱼柳 150 g",
      "海苔 1 片",
      "浅色味噌 20 g",
      "老豆腐 150 g",
      "裙带菜（干） 2 g",
      "水 900 ml",
      "低钠酱油 10 ml",
    ],
    steps: [
      "煮米；三文鱼蒸/煮8–10分钟至全熟，撕碎包入饭团，外裹海苔。",
      "味噌用热水化开（不沸腾）；下豆腐与裙带菜焖2–3分钟。",
      "少量酱油调整。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈78 g KH · 孕期✓ 鱼全熟、海藻少量",
    swaps: "寿司米 ↔ 糙米；三文鱼 ↔ 明太鱼/狭鳕。",
    side: "温和绿茶（可脱咖）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Two salmon onigiri and a small bowl of miso soup"),
  },
  {
    id: "di-m",
    title: "鸡肉河粉炒（河粉）",
    desc: "广式灵感，蔬菜多，口味温和。",
    story: "参考广东Ho Fun，快手均衡，适合工作日午餐。Inspiration: inspiriert von The Woks of Life",
    target: "≈74 g KH gesamt (2 P.) · 蛋白质 ≈39 g/人",
    ingredients: [
      "干河粉 80 g",
      "鸡胸肉 250 g",
      "彩椒 150 g",
      "小白菜 200 g",
      "洋葱 80 g",
      "胡萝卜 100 g",
      "低钠酱油 25 ml",
      "香油 10 ml",
    ],
    steps: [
      "河粉浸泡/焯水3–4分钟。",
      "鸡丝少油翻炒5–6分钟至全熟。",
      "下蔬菜翻炒3–4分钟，温和调味。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈74 g KH · 孕期✓ 鸡肉全熟",
    swaps: "河粉 ↔ 乌冬；鸡肉 ↔ 豆腐。",
    side: "黄瓜片原味。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Stir-fried rice noodles with chicken and vegetables, no chili"),
  },
  {
    id: "di-a",
    title: "大酱汤配麦仁（된장찌개）",
    desc: "韩式大酱锅，醇厚不辣，配珍珠麦。",
    story: "家常暖汤，秋冬尤佳；风味足但温和。Inspiration: inspiriert von Seon Kyoung Longest",
    target: "≈86 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "大酱 30 g",
      "老豆腐 300 g",
      "西葫芦 200 g",
      "土豆 200 g",
      "香菇 100 g",
      "洋葱 70 g",
      "水 800 ml",
      "低钠酱油 10 ml",
      "珍珠麦（生） 70 g",
    ],
    steps: [
      "大酱溶于水，蔬菜小火煮12–15分钟。",
      "入豆腐丁略焖3–4分钟。",
      "珍珠麦另煮25–30分钟，搭配食用。",
    ],
    checks: "胃炎——醇厚不辣 · 糖友✓ ≈86 g KH · 孕期✓ 全熟",
    swaps: "珍珠麦 ↔ 米饭；豆腐 ↔ 火鸡胸。",
    side: "温和腌黄瓜（无辣）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Korean soybean stew with tofu and vegetables, side of barley"),
  },

  // 周三
  {
    id: "mi-f",
    title: "南瓜粥配豆腐与毛豆（단호박죽）",
    desc: "丝滑米粥，高蛋白、低钠。",
    story: "韩国应季做法，口感细腻、暖胃。Inspiration: inspiriert von Mom's Korean Recipes",
    target: "≈75 g KH gesamt (2 P.) · 蛋白质 ≈22 g/人",
    ingredients: [
      "南瓜 400 g",
      "大米（生） 70 g",
      "老豆腐 200 g",
      "毛豆仁 100 g",
      "姜 8 g",
      "水 900 ml",
      "盐 一撮",
    ],
    steps: [
      "南瓜+大米小火煮25分钟。",
      "打成细腻；入豆腐与毛豆再煮3–4分钟。",
      "温和调味即可。",
    ],
    checks: "胃炎——软暖 · 糖友✓ ≈75 g KH · 孕期✓ 全熟",
    swaps: "毛豆 ↔ 白腰豆；豆腐 ↔ 鸡胸丁。",
    side: "温热米茶/大麦茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Golden pumpkin rice porridge with tofu and edamame"),
  },
  {
    id: "mi-m",
    title: "鸡肉西兰花乌冬汤（うどん）",
    desc: "清汤乌冬，轻柔饱腹。",
    story: "轻汤乌冬在日本很常见，适合不吃辣的午餐。Inspiration: inspiriert von Just One Cookbook",
    target: "≈79 g KH gesamt (2 P.) · 蛋白质 ≈34 g/人",
    ingredients: [
      "乌冬（干） 100 g",
      "鸡胸肉 220 g",
      "西兰花 200 g",
      "洋葱 60 g",
      "浅色味噌 25 g",
      "水 1000 ml",
      "低钠酱油 15 ml",
    ],
    steps: [
      "味噌+酱油调汤加热（不沸腾）。",
      "鸡肉小火煮6–8分钟至全熟；蔬菜再煮3–4分钟。",
      "乌冬另煮8–10分钟，冲洗后入汤。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈79 g KH · 孕期✓ 鸡肉全熟",
    swaps: "乌冬 ↔ 荞麦面；鸡肉 ↔ 豆腐。",
    side: "小碟黄瓜。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Light udon soup with chicken and broccoli"),
  },
  {
    id: "mi-a",
    title: "姜丝清蒸鳕鱼 & 米饭（清蒸鳕鱼）",
    desc: "粤式清蒸，细嫩易消化。",
    story: "清蒸是粤菜经典技法，味轻不腻。Inspiration: inspiriert von Made With Lau",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "鳕鱼柳 320 g",
      "大米（生） 90 g",
      "姜 15 g",
      "葱 30 g",
      "低钠酱油 15 ml",
      "香油 8 ml",
      "蔬菜高汤 100 ml",
    ],
    steps: [
      "鱼置姜片上蒸8–10分钟至全熟。",
      "酱油+高汤加热浇鱼，淋少许香油。",
      "米饭煮熟同食。",
    ],
    checks: "胃炎——清蒸 · 糖友✓ ≈70 g KH · 孕期✓ 鳕鱼全熟、低汞",
    swaps: "鳕鱼 ↔ 明太鱼；米饭 ↔ 糙米。",
    side: "清蒸西兰花。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Steamed cod with ginger and scallions, small bowl of rice"),
  },

  // 周四
  {
    id: "do-f",
    title: "玉子烧 & 味噌汤配小碗米饭（卵焼き・味噌汁）",
    desc: "日式早餐，鸡蛋完全凝固。",
    story: "玉子烧常见于日式早餐与便当，口味温和均衡。Inspiration: inspiriert von Just One Cookbook",
    target: "≈62 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "鸡蛋 4 枚",
      "老豆腐 150 g",
      "大米（生） 80 g",
      "浅色味噌 20 g",
      "裙带菜（干） 1 g",
      "葱 20 g",
      "水 800 ml",
      "低钠酱油 10 ml",
    ],
    steps: [
      "煮饭；玉子烧卷煎5–6分钟至完全凝固。",
      "煮味噌汤；下豆腐与裙带菜焖2–3分钟。",
      "撒葱花上桌。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈62 g KH · 孕期✓ 蛋完全凝固",
    swaps: "米饭 ↔ 糙米；豆腐 ↔ 鸡胸丁。",
    side: "温热绿茶（低咖）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Japanese breakfast with rolled omelet, miso soup, small rice bowl"),
  },
  {
    id: "do-m",
    title: "番茄炒蛋配豆腐 & 米饭（番茄炒蛋）",
    desc: "家常酸甜，炖软更温和。",
    story: "番茄炒蛋是中国最受欢迎的家常菜之一，工作日快手之选。Inspiration: inspiriert von The Woks of Life",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈28 g/人",
    ingredients: [
      "大米（生） 90 g",
      "鸡蛋 4 枚",
      "老豆腐 200 g",
      "熟透番茄 400 g",
      "洋葱 60 g",
      "低钠酱油 10 ml",
      "菜籽油 10 ml",
    ],
    steps: [
      "煮饭；鸡蛋炒3–4分钟至全熟。",
      "番茄/洋葱小火炖6–8分钟；入豆腐略焖。",
      "温和调味，配米饭。",
    ],
    checks: "胃炎——酸度温和、炖至软 · 糖友✓ ≈70 g KH · 孕期✓ 蛋全熟",
    swaps: "豆腐 ↔ 火鸡胸丁；米饭 ↔ 糙米。",
    side: "清蒸小白菜。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Tomato and egg stir-fry with tofu, served with rice"),
  },
  {
    id: "do-a",
    title: "温和韩式烤肉风味火鸡 & 糙米（불고기）",
    desc: "平底锅快炒版，甜咸适中，辣椒分开给。",
    story: "烤肉来自韩国，快手家常非常受欢迎。Inspiration: inspiriert von Maangchi",
    target: "≈80 g KH gesamt (2 P.) · 蛋白质 ≈28 g/人",
    ingredients: [
      "火鸡胸肉 250 g",
      "糙米（生） 90 g",
      "洋葱 80 g",
      "胡萝卜 120 g",
      "蘑菇 150 g",
      "低钠酱油 25 ml",
      "香油 10 ml",
      "蒜 1 瓣",
      "梨（擦泥） 60 g",
    ],
    steps: [
      "火鸡与酱油/梨泥/蒜腌15分钟。",
      "少油快炒5–6分钟至全熟。",
      "入蔬菜略炒3–4分钟；配糙米。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈80 g KH · 孕期✓ 全熟",
    swaps: "火鸡 ↔ 鸡胸；糙米 ↔ 白米。",
    side: "黄瓜片原味；温和白萝卜浅渍。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Mild bulgogi-style turkey with vegetables, brown rice, no chili"),
  },

  // 周五
  {
    id: "fr-f",
    title: "鸡肉粥（鸡肉粥）",
    desc: "中式米粥，鸡肉嫩滑，极为温和。",
    story: "华南与东南亚常见的安慰系早餐/夜宵。Inspiration: inspiriert von The Woks of Life",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈34 g/人",
    ingredients: [
      "大米（生） 90 g",
      "鸡胸肉 220 g",
      "姜 12 g",
      "胡萝卜 120 g",
      "水 1100 ml",
      "低钠酱油 10 ml",
      "葱 20 g",
    ],
    steps: [
      "米加水小火煮30分钟。",
      "鸡丁入粥煮8–10分钟至全熟。",
      "温和调味，撒葱花。",
    ],
    checks: "胃炎——非常温和 · 糖友✓ ≈70 g KH · 孕期✓ 全熟",
    swaps: "鸡肉 ↔ 豆腐；胡萝卜 ↔ 南瓜。",
    side: "温热花草茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Chicken congee with scallions, gentle steam"),
  },
  {
    id: "fr-m",
    title: "清爽意式蔬菜汤配豆腐（Minestrone）",
    desc: "久煮温和、富含蔬菜与豆类，低钠。",
    story: "Minestrone 是温暖而不厚重的意式蔬菜汤。Inspiration: inspiriert von Giallo Zafferano",
    target: "≈69 g KH gesamt (2 P.) · 蛋白质 ≈30 g/人",
    ingredients: [
      "全麦通心粉（干） 80 g",
      "老豆腐 200 g",
      "白腰豆（熟） 200 g",
      "胡萝卜 150 g",
      "西芹 100 g",
      "西葫芦 150 g",
      "番茄丁（罐） 200 g",
      "蔬菜高汤 800 ml",
      "橄榄油 10 ml",
    ],
    steps: [
      "少油炒香蔬菜4–5分钟，加高汤。",
      "小火煮15–20分钟；入面8–10分钟。",
      "下豆腐和豆子再煮3–4分钟，温和调味。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈69 g KH · 孕期✓ 全熟",
    swaps: "全麦面 ↔ 大麦；豆腐 ↔ 鸡胸。",
    side: "黄瓜沙拉（低酸）。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Light Italian minestrone with vegetables, beans and tofu"),
  },
  {
    id: "fr-a",
    title: "烤箱照烧三文鱼 & 西兰花、白米（照り焼き鮭）",
    desc: "低钠照烧，烤熟更温和，甜咸适口。",
    story: "照烧是日本常见的酱烤技法，这里减盐减甜做成孕期友好版。Inspiration: inspiriert von Just One Cookbook",
    target: "≈77 g KH gesamt (2 P.) · 蛋白质 ≈30 g/人",
    ingredients: [
      "三文鱼柳 320 g",
      "大米（生） 90 g",
      "西兰花 250 g",
      "低钠酱油 20 ml",
      "蜂蜜 10 g",
      "水 30 ml",
      "姜 6 g",
    ],
    steps: [
      "煮饭30分钟。",
      "三文鱼刷酱（酱油/水/蜂蜜/姜），180°C 烤12–14分钟至全熟。",
      "西兰花蒸4–5分钟，配饭同食。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈77 g KH · 孕期✓ 鱼全熟、低汞",
    swaps: "三文鱼 ↔ 鳕鱼；米饭 ↔ 糙米。",
    side: "温热绿茶；温和白萝卜浅渍。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Oven-baked teriyaki salmon with steamed broccoli and rice"),
  },

  // 周六
  {
    id: "sa-f",
    title: "鸡肉杂炊蔬菜饭汤（雑炊）",
    desc: "利用剩饭的日式汤饭，轻盈暖胃。",
    story: "杂炊是日本的安慰系家常，柔软易消化。Inspiration: inspiriert von Just One Cookbook",
    target: "≈68 g KH gesamt (2 P.) · 蛋白质 ≈22 g/人",
    ingredients: [
      "熟米饭 250 g",
      "鸡胸肉 150 g",
      "胡萝卜 100 g",
      "香菇 80 g",
      "鸡蛋 1 枚",
      "清汤 700 ml",
      "低钠酱油 10 ml",
      "葱 15 g",
    ],
    steps: [
      "汤加热；鸡丁小火煮6–7分钟至全熟。",
      "入米饭煮5分钟；打散蛋液倒入并完全凝固1–2分钟。",
      "少量酱油调味，撒葱花。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈68 g KH · 孕期✓ 蛋完全凝固",
    swaps: "鸡肉 ↔ 豆腐；米饭 ↔ 糙米。",
    side: "茉莉花茶淡泡。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Comforting Japanese zosui rice soup with chicken and set egg"),
  },
  {
    id: "sa-m",
    title: "温热荞麦面配豆腐与菠菜（そば）",
    desc: "清汤荞麦面，蔬菜多、低钠。",
    story: "荞麦面在日本广受喜爱；这一碗以清淡为主，适合午餐。Inspiration: inspiriert von MAFF Japan",
    target: "≈72 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "荞麦面（干） 90 g",
      "老豆腐 200 g",
      "菠菜 200 g",
      "香菇 80 g",
      "浅色味噌 20 g",
      "高汤/水 900 ml",
      "低钠酱油 10 ml",
    ],
    steps: [
      "汤底以味噌+酱油加热（不沸）。",
      "荞麦面煮6–7分钟，冲洗后入汤。",
      "豆腐/菠菜/香菇焖2–3分钟。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈72 g KH · 孕期✓ 全熟",
    swaps: "荞麦面 ↔ 乌冬；豆腐 ↔ 鸡胸。",
    side: "黄瓜原味；温和浅渍。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Warm soba noodle soup with tofu, spinach and mushrooms"),
  },
  {
    id: "sa-a",
    title: "白菜豆腐煮 & 白米（白菜豆腐煮）",
    desc: "清淡炖煮，素口味，易消化。",
    story: "北方家常风，柔软味轻，适合晚间。Inspiration: inspiriert von The Hong Kong Cookery",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈24 g/人",
    ingredients: [
      "大白菜 500 g",
      "老豆腐 300 g",
      "大米（生） 90 g",
      "姜 8 g",
      "蒜 1 瓣",
      "低钠酱油 15 ml",
      "蔬菜高汤 250 ml",
      "玉米淀粉 8 g",
    ],
    steps: [
      "煮饭；白菜入汤小火炖8–10分钟。",
      "入豆腐再煨3–4分钟。",
      "勾薄芡后浇在米饭上。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 全熟",
    swaps: "豆腐 ↔ 鸡胸；米饭 ↔ 糙米。",
    side: "温热黄瓜浅渍（无辣）。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Braised napa cabbage with tofu in light sauce, with rice"),
  },

  // 周日
  {
    id: "so-f",
    title: "红薯日式米粥配豆腐（さつまいも粥）",
    desc: "柔和米粥，带自然甜味，低钠。",
    story: "Okayu 的自然变体，适合需要温暖的一天。Inspiration: inspiriert von Just One Cookbook",
    target: "≈75 g KH gesamt (2 P.) · 蛋白质 ≈20 g/人",
    ingredients: [
      "大米（生） 80 g",
      "红薯 250 g",
      "内酯豆腐 180 g",
      "水 900 ml",
      "姜 6 g",
      "低钠酱油 8 ml",
    ],
    steps: [
      "米加水煮25–30分钟至粥。",
      "入红薯丁煮10–12分钟至软。",
      "入豆腐微调味。",
    ],
    checks: "胃炎——温和柔软 · 糖友✓ ≈75 g KH · 孕期✓ 全熟",
    swaps: "红薯 ↔ 南瓜；内酯豆腐 ↔ 老豆腐。",
    side: "温热焙茶。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Okayu with sweet potato and silken tofu, gentle steam"),
  },
  {
    id: "so-m",
    title: "猪肉味噌汤 & 米饭（豚汁）",
    desc: "浓而不重，根茎蔬菜丰富。",
    story: "豚汁是日本冬季人气汤品，饱腹而温和。Inspiration: inspiriert von Just One Cookbook",
    target: "≈70 g KH gesamt (2 P.) · 蛋白质 ≈30 g/人",
    ingredients: [
      "瘦猪肉片 220 g",
      "浅色味噌 25 g",
      "土豆 200 g",
      "胡萝卜 120 g",
      "洋葱 60 g",
      "高汤/水 900 ml",
      "大米（生） 90 g",
    ],
    steps: [
      "煮饭；味噌调汤。",
      "猪肉小火煮8–10分钟至全熟。",
      "蔬菜再煮10–12分钟至软。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈70 g KH · 孕期✓ 肉全熟",
    swaps: "猪肉 ↔ 鸡肉；米饭 ↔ 糙米。",
    side: "黄瓜浅渍（无辣）。",
    remind: false,
    prompt: buildPrompt(PROMPT_HEADER, "Japanese tonjiru with root vegetables, side of rice"),
  },
  {
    id: "so-a",
    title: "寿喜烧风牛肉蔬煮 & 小份米饭（すき焼き風）",
    desc: "甜咸轻口味，小份米饭更均衡。",
    story: "寿喜烧是日本合家欢的锅物，这里不配生蛋，温和更安心。Inspiration: inspiriert von Just One Cookbook",
    target: "≈62 g KH gesamt (2 P.) · 蛋白质 ≈32 g/人",
    ingredients: [
      "瘦牛肉片 240 g",
      "洋葱 80 g",
      "香菇 100 g",
      "大白菜 300 g",
      "低钠酱油 20 ml",
      "味醂 10 ml",
      "水 200 ml",
      "大米（生） 80 g",
    ],
    steps: [
      "煮饭。",
      "蔬菜小火炖6–8分钟，入酱汁。",
      "牛肉煮2–3分钟至全熟即可。",
    ],
    checks: "胃炎——温和 · 糖友✓ ≈62 g KH · 孕期✓ 不用生蛋、肉全熟",
    swaps: "牛肉 ↔ 火鸡；米饭 ↔ 糙米。",
    side: "温热绿茶；白萝卜浅渍。",
    remind: true,
    prompt: buildPrompt(PROMPT_HEADER, "Sukiyaki-style beef with vegetables, small bowl of rice, no raw egg"),
  },
];

/* ---------- Export minimal container ---------- */
export default function PlanZH() {
  return (
    <div style={{ display: "none" }} data-file-base={FILE_BASE} data-title-main={UI_TITLES.main} data-title-list={UI_TITLES.list} data-count={DATA.length} data-lang="zh" />
  );
}

export const DATASET = DATA;
export const COLORS_CONST = COLORS;
export const PROMPT_HEADER_CONST = PROMPT_HEADER;
